services:
  postgres:
    image: postgres:16-alpine
    container_name: ems_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ems_network

  redis:
    image: redis:alpine
    container_name: ems_redis
    ports:
      - "6379:6379"
    networks:
      - ems_network

  backend:
    build: ./backend
    container_name: ems_backend
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: supersecretkey
      JWT_EXPIRATION: 1d
    depends_on:
      - postgres
      - redis
    networks:
      - ems_network

volumes:
  postgres_data:

networks:
  ems_network:
